name: aerospike-service

director_uuid: REPLACE_WITH_DIRECTOR_UUID

releases:
- {name: REPLACE_WITH_RELEASE_NAME, version: latest}

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3147

instance_groups:
- name: server
  instances: 1
  vm_type: container
  persistent_disk_type: ten
  azs: [lite]
  networks:
    - name: kafka
  stemcell: trusty
  jobs:
  - name: aerospike-server
    instances: 1
    templates:
    - {name: aerospike-server, release: REPLACE_WITH_RELEASE_NAME}
    vm_type: REPLACE_WITH_VM_TYPE_FROM_DIRECTOR_CLOUD_CONFIG
    persistent_disk_type: REPLACE_WITH_PERSISTENT_DISK_TYPE_FROM_CLOUD_CONFIG
    stemcell: trusty
    networks:
    - name: REPLACE_WITH_NETWORK_FROM_DIRECTOR_CLOUD_CONFIG

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 15000-30000
  update_watch_time: 15000-300000
