#!/bin/bash
set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

JOB_NAME=route-registrar

RUN_DIR=/var/vcap/sys/run/aerospike-amc
LOG_DIR=/var/vcap/sys/log/aerospike-amc
PIDFILE=$RUN_DIR/route-registrar.pid
CONFIG_FILE=/var/vcap/jobs/aerospike-amc/config/registrar_settings.yml

source /var/vcap/packages/common/utils.sh

export HOME=/var/vcap

case $1 in

start)
  mkdir -p $RUN_DIR $LOG_DIR
  chown vcap:vcap $RUN_DIR $LOG_DIR

  pid_guard $PIDFILE $JOB_NAME

  # Copy the config file to right folder
  cp /var/vcap/jobs/aerospike-amc/config/registrar_settings.yml /var/vcap/packages/route-registrar/registrar_settings.yml

  # registrar_settings.yml must be in pwd
  cd /var/vcap/packages/route-registrar

  su vcap -c "/var/vcap/packages/route-registrar/bin/route-registrar \
  -pidfile=$PIDFILE \
  -configPath=$CONFIG_FILE \
  >>$LOG_DIR/route-registrar.stdout.log \
  2>>$LOG_DIR/route-registrar.stderr.log &"
;;

stop)
  kill_and_wait $PIDFILE
;;

*)
echo "Usage: route_registrar_ctl {start|stop}" ;;

esac
exit 0
